### ISSUE TITLE
Update ms-rest-js dependency

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/ms-rest-browserauth#29]
By staying on v1 of `@azure/ms-rest-js`, this package is not usable on azure sdks that have moved on to using v2 of `@azure/ms-rest-js`.

The counterpart to this package in node is `@azure/ms-rest-nodeauth` that has long since released a major version update after upgrading to use v2 of `@azure/ms-rest-js` as below
```
"@azure/ms-rest-azure-env": "^2.0.0",
"@azure/ms-rest-js": "^2.0.4",
```

This issue is to request the same change to this package.
This will be a breaking change and therefore will need a major version update from 0 to 1
With this change,

- Azure SDKs that have moved on to using v2 of `@azure/ms-rest-js` will need v3 of `@azure/ms-rest-nodeauth` if using node or v1 of @azure/ms-rest-browserauth
- Azure SDKs that are still using v1 of `@azure/ms-rest-js` will need v2 of `@azure/ms-rest-nodeauth` if using node or v0 of @azure/ms-rest-browserauth

cc @HarshaNalluru, @daviwil

**Comment by HarshaNalluru** [comment]
#30

**Comment by ramya-rao-a** [comment]
Thanks @HarshaNalluru!

The version 1.0.0 of this package now has the updated dependencies
